### ISSUE TITLE
Deprecated TaskInputs and TaskOutputs methods

### ISSUE THREAD

**Issue by wilsonmar** [docker-production-aws/microtrader-base#3] opened 2018-10-11 11:07 UTC
When I ran "./gradlew clean test shadowjar" it ended with
```
BUILD SUCCESSFUL in 1m 24s
37 actionable tasks: 31 executed, 6 up-to-date
```
However, messages such as these appear:
```
> Task :shadowJar 
A problem was found with the configuration of task ':shadowJar'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - No value has been specified for property 'mainClassName'.
```
I am using macOS High Sierra, uname -a
```
Darwin Wilsons-MBP 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```
$ ./gradlew -version
```
Gradle 4.3.1
Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by mixja** [comment] 2018-10-11 11:46
Duplicate of https://github.com/docker-production-aws/microtrader/issues/1

**Closed as completed by mixja** 2018-10-11 11:46 UTC
